# Generated by Django 4.2 on 2026-03-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashforecastitem',
            name='recurrence_period',
            field=models.CharField(blank=True, choices=[('MONTHLY', 'Mensuel'), ('QUARTERLY', 'Trimestriel'), ('YEARLY', 'Annuel')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cashforecastitem',
            name='type',
            field=models.CharField(choices=[('INCOME', 'Encaissement'), ('EXPENSE', 'Décaissement')], max_length=10),
        ),
    ]
