# Generated by Django 4.2 on 2026-03-25 15:32

import apps.core.models
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('due_date', models.DateField()),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('client_address', models.TextField(blank=True, null=True)),
                ('client_siret', apps.core.models.EncryptedTextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('SENT', 'SENT'), ('PAID', 'PAID'), ('OVERDUE', 'OVERDUE'), ('CANCELLED', 'CANCELLED')], default='DRAFT', max_length=20)),
                ('total_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('reminder_count', models.PositiveIntegerField(default=0)),
                ('last_reminder_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('valid_until', models.DateField()),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('client_address', models.TextField(blank=True, null=True)),
                ('client_siret', apps.core.models.EncryptedTextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('SENT', 'SENT'), ('ACCEPTED', 'ACCEPTED'), ('REFUSED', 'REFUSED'), ('EXPIRED', 'EXPIRED')], default='DRAFT', max_length=20)),
                ('total_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_rate', models.DecimalField(choices=[(Decimal('20.0'), '20%'), (Decimal('10.0'), '10%'), (Decimal('5.5'), '5.5%'), (Decimal('0.0'), '0%')], decimal_places=2, default=Decimal('20.0'), max_digits=6)),
                ('amount_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('amount_ttc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoicing.invoice')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoicing.quote')),
            ],
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['company', 'date'], name='invoicing_q_company_307bef_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['company', 'status'], name='invoicing_q_company_e954f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together={('company', 'number')},
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['invoice'], name='invoicing_i_invoice_7eb31c_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['quote'], name='invoicing_i_quote_i_724291_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'date'], name='invoicing_i_company_f943d1_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'status'], name='invoicing_i_company_1397b8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('company', 'number')},
        ),
    ]
