# Generated by Django 4.2 on 2026-03-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SENT', 'Envoyée'), ('PAID', 'Payée'), ('OVERDUE', 'En retard'), ('CANCELLED', 'Annulée')], default='DRAFT', max_length=20),
        ),
    ]
