# Generated by Django 4.2 on 2026-03-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_invoice_status_labels_fr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SENT', 'Envoyé'), ('ACCEPTED', 'Accepté'), ('REFUSED', 'Refusé'), ('EXPIRED', 'Expiré')], default='DRAFT', max_length=20),
        ),
    ]
