# Generated by Django 4.2 on 2026-03-25 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoicing', '0003_status_labels_fr'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SENT', 'Envoyé'), ('ACCEPTED', 'Accepté'), ('REFUSED', 'Refusé'), ('EXPIRED', 'Expiré'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='BillingDocumentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('QUOTE', 'Devis'), ('INVOICE', 'Facture')], max_length=10)),
                ('document_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('CREATED', 'Création'), ('UPDATED', 'Modification'), ('CANCELLED', 'Annulation'), ('STATUS_CHANGED', 'Changement de statut')], max_length=20)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_histories', to='core.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_history_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('QUOTE', 'Devis'), ('INVOICE', 'Facture')], max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('next_seq', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sequences', to='core.company')),
            ],
            options={
                'unique_together': {('company', 'kind', 'year')},
            },
        ),
        migrations.AddIndex(
            model_name='billingdocumenthistory',
            index=models.Index(fields=['company', 'kind', 'document_id'], name='invoicing_b_company_2765bf_idx'),
        ),
    ]
